name: .NET Desktop CI

on:
  push:
    branches:
      - main

env:
  WINDOWS_ZIP: GenelecWakeSleep-windows-v1.0.${{ github.run_number }}.zip
  LINUX_ZIP: GenelecWakeSleep-linux-v1.0.${{ github.run_number }}.zip
  OSX_INTEL_ZIP: GenelecWakeSleep-osx-intel-v1.0.${{ github.run_number }}.zip
  OSX_ARM_ZIP: GenelecWakeSleep-osx-arm-v1.0.${{ github.run_number }}.zip

jobs:
  build_and_release:
    permissions: write-all
    runs-on: macos-12
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore GenelecApp.sln

    - name: Build for Windows
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true /p:DebugType=None /p:DebugSymbols=false -o ./binaries/win-x64 GenelecApp.sln

    - name: Build for Linux
      run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true /p:DebugType=None /p:DebugSymbols=false -o ./binaries/linux-x64 GenelecApp.sln

    - name: Build for macOS (Intel)
      run: dotnet publish -c Release -r osx-x64 -p:PublishSingleFile=true --self-contained true /p:DebugType=None /p:DebugSymbols=false -o ./binaries/osx-x64 GenelecApp.sln

    - name: Build for macOS (ARM)
      run: dotnet publish -c Release -r osx-arm64 -p:PublishSingleFile=true --self-contained true /p:DebugType=None /p:DebugSymbols=false -o ./binaries/osx-arm GenelecApp.sln

    - name: Set permissions
      run: |
        chmod +x ./binaries/linux-x64/GenelecApp
        chmod +x ./binaries/linux-x64/libhidapi-hidraw.so.0
        chmod +x ./binaries/osx-x64/GenelecApp
        chmod +x ./binaries/osx-arm/GenelecApp
        
    - name: Archive binaries
      run: |
        zip -FSrj ./binaries/${{ env.WINDOWS_ZIP }} ./binaries/win-x64/*
        zip -FSrj ./binaries/${{ env.LINUX_ZIP }} ./binaries/linux-x64/*
        zip -FSrj ./binaries/${{ env.OSX_INTEL_ZIP }} ./binaries/osx-x64/*
        zip -FSrj ./binaries/${{ env.OSX_ARM_ZIP }} ./binaries/osx-arm/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number-22 }}
        release_name: Release v1.0.${{ github.run_number-22 }}
        draft: false
        prerelease: false

    - name: Attach Windows binaries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/${{ env.WINDOWS_ZIP }}
        asset_name: ${{ env.WINDOWS_ZIP }}
        asset_content_type: application/zip

    - name: Attach Linux binaries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/${{ env.LINUX_ZIP }}
        asset_name: ${{ env.LINUX_ZIP }}
        asset_content_type: application/zip

    - name: Attach macOS (Intel) binaries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/${{ env.OSX_INTEL_ZIP }}
        asset_name: ${{ env.OSX_INTEL_ZIP }}
        asset_content_type: application/zip

    - name: Attach macOS (ARM) binaries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binaries/${{ env.OSX_ARM_ZIP }}
        asset_name: ${{ env.OSX_ARM_ZIP }}
        asset_content_type: application/zip
