name: Build Linux Packages

on:
  push:
    branches:
      - workflow-test

env:
  DIST: el7
  ARCH: noarch

jobs:
  build_tarball:
    name: Build source archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Replace version in RPM spec
      #   run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{ github.ref_name }}/' ${{ vars.PKG_NAME }}.spec

      - name: Create source archive
        run: tar -czvf ${{ vars.PKG_NAME }}-${{ github.ref_name }}.tar.gz *

      - name: Upload source archive
        uses: actions/upload-artifact@v4
        with:
          name: source-archive
          path: ${{ vars.PKG_NAME }}-${{ github.ref_name }}.tar.gz

  build_rpm:
    name: Build .rpm package
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Replace version in RPM spec
      #   run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{ github.ref_name }}/' ${{ vars.PKG_NAME }}.spec
      #
      # - name: Setup Rust
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     target: x86_64-unknown-linux-gnu
      #     default: true
      #
      # - name: Install HIDAPI Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libhidapi-dev libudev-dev

      - name: Build RPM
        id: rpm
        uses: stephanmeesters/rpmbuild@master
        with:
          spec_file: ${{ vars.PKG_NAME }}.spec

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: rpmbuild/RPMS/${{ env.ARCH }}/*.rpm

  build_deb:
    name: Build .deb package
    needs: build_rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download RPM
        uses: actions/download-artifact@v4
        with:
          name: rpm-package

      - name: Convert .rpm to .deb
        run: |
          sudo apt update
          sudo apt install -y alien
          sudo alien -k --verbose --to-deb *.rpm

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ${{ vars.PKG_NAME }}*.deb

  release:
    name: Release
    needs: [build_tarball, build_rpm, build_deb]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download tarball
        uses: actions/download-artifact@v4
        with:
          name: source-archive
          path: release-assets

      - name: Download RPM
        uses: actions/download-artifact@v4
        with:
          name: rpm-package
          path: release-assets

      - name: Download DEB
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: release-assets

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes "Automated release for version ${{ github.ref_name }}" \
            release-assets/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

